class Calc:
    def Add(self,a,b):
        return a+b
    def subtrcation(self,a,b):
        return a-b
    def multiplication(self,a,b):
        return a*b
    def division(self,a,b):
        return a/b
